blank_issues_enabled: false
contact_links:
  - name: Victron Community - Node-RED
    url: https://community.victronenergy.com/c/node-red/28
    about: Ask general Node-RED / Victron questions on the community forum
